swagger: "2.0"
info:
  version: 1.0.0
  title: onboard-api
  description: oboard-api
basePath: /api/v1
tags:
  - name: Specification
    description: The swagger API specification
  - name: Member
    description: Simple member endpoints
  - name: Member type
    description: Tipo de membros

consumes:
  - application/json
produces:
  - application/json


definitions:
  MemberBody:
    type: object
    title: Member
    required:
      - name
      - email
      - status
      - memberTypeId
    properties:
      name:
        type: string
        example: Mateus Henrique
      phone:
        type: string
        example: (81) 973248345
      email:
        type: string
        example: mateus.morais@maxxidata.com
      status:
        type: string
        example: pending
      memberTypeId:
        type: number
        example: 1
      street:
        type: string
        example: Rua Ayres da Cunha
      number:
        type: string
        example: 96
      neighborhood:
        type: string
        example: Mauricio de Nassau
      city:
        type: string
        example: Caruaru
      state:
        type: string
        example: Pernambuco
  UpdateMemberBody:
    type: object
    title: Member
    required:
      - name
      - status
      - memberTypeId
    properties:
      name:
        type: string
        example: Mateus Henrique
      phone:
        type: string
        example: (81) 973248345
      memberTypeId:
        type: number
        example: 1
      status:
        type: string
        example: pending
  MemberTypeBody:
    type: object
    title: Member type
    required:
      - description
      - status
    properties:
      description:
        type: string
        example: Administradores
      status:
        type: string
        example: pending
  

paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification


  /member:
    get:
      tags:
        - Member
      description: Lista todos os membros
      parameters:
        - in: query
          name: page
          description: Número da página que deseja acessar
          required: false
          default: 1
          type: number
        - in: query
          name: limit 
          description: Número de itens por página
          default: 20 
          type: number
      responses:
        200:
          description: Lista todos os membros
    post:
      tags:
        - Member
      description: Cria um novo membro
      parameters:
        - name: Membro
          in: body
          description: Membro que deseja adicionar
          schema: 
            $ref: "#/definitions/MemberBody"
      responses:
        201:
          description: Retorna o objeto do membro criado
        400:
          description: Objeto de membro inválido
    put:
      tags:
        - Member
      description: Atualiza um membro já existente
      parameters:
        - name: Membro
          in: body
          description: Membro que deseja atualizar
          schema:
            $ref: '#/definitions/UpdateMemberBody'
      responses:
        200:
          description: Retorna o objeto do membro atualizado
        400:
          description: Objeto de membro inválido
  /member-type:
    get:
      tags:
        - MemberType
      description: Lista todos os tipos de membros
      parameters:
        - in: query
          name: page
          description: Número da página que deseja acessar
          required: false
          default: 1
          type: number
        - in: query
          name: limit 
          description: Número de itens por página
          default: 20 
          type: number
      responses:
        200:
          description: Lista todos os tipos de membros
    post: 
      tags: 
        - MemberType
      description: Cria um novo tipo de membro
      parameters:
        - name: Tipo de membro
          in: body
          description: Tipo de membro que deseja adicionar
          schema:
            $ref: '#/definitions/MemberTypeBody'
      responses:
        201:
          description: Retorna o objedo de tipo de membro criado
        400:
          description: Objeto de tipo de membro inválido



  